/**
 * sync/generators/readme.ts — Documentation README generator
 */

import type { SyncableDesignSystem } from "../../versions/types.js";
import { extractTypographyScales } from "./tokens.js";

/**
 * Generates a README.md file documenting the exported design system.
 */
export function generateReadme(designSystem: SyncableDesignSystem): string {
  const { tokens, name, currentVersion } = designSystem;
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const lines: string[] = [];

  lines.push(`# ${name}`);
  lines.push(`Version ${currentVersion} — generated by Styled Systems on ${date}`);
  lines.push("");

  // Installation
  lines.push("## Usage");
  lines.push("");
  lines.push("### Tailwind CSS");
  lines.push("```js");
  lines.push("// tailwind.config.js");
  lines.push("module.exports = {");
  lines.push("  presets: [require('./tailwind.config.js')],");
  lines.push("}");
  lines.push("```");
  lines.push("");
  lines.push("### CSS Custom Properties");
  lines.push("```css");
  lines.push("@import './variables.css';");
  lines.push("");
  lines.push("body {");
  if (tokens.fontFamilies?.[0]) {
    lines.push(`  font-family: var(--font-${tokens.fontFamilies[0].type});`);
  }
  lines.push("}");
  lines.push("```");
  lines.push("");
  lines.push("### InDesign");
  lines.push(
    "Open `design-system.idml` in Adobe InDesign to access all paragraph styles, character styles, and color swatches."
  );
  lines.push("");

  // Files
  lines.push("## Files");
  lines.push("");
  lines.push("| File | Description |");
  lines.push("|------|-------------|");
  lines.push("| `tokens.json` | W3C Design Token Format |");
  lines.push("| `tailwind.config.js` | Tailwind CSS v3 preset |");
  lines.push("| `variables.css` | CSS custom properties |");
  lines.push("| `figma-tokens.json` | Tokens Studio plugin format |");
  lines.push("| `figma-variables.json` | Figma native variables format |");
  lines.push("| `design-system.idml` | InDesign template |");
  lines.push("| `assets/` | Logos and brand assets |");
  lines.push("");

  // Typography
  if (tokens.typography) {
    const scales = extractTypographyScales(tokens.typography);
    if (scales.length) {
      lines.push("## Typography");
      lines.push("");
      lines.push("| Token | Size | Line Height |");
      lines.push("|-------|------|-------------|");
      for (const s of scales) {
        lines.push(`| \`${s.token}\` | ${s.fontSize}px | ${s.lineHeight}px |`);
      }
      lines.push("");
    }
  }

  // Font families
  if (tokens.fontFamilies?.length) {
    lines.push("## Font Families");
    lines.push("");
    for (const ff of tokens.fontFamilies) {
      lines.push(`- **${ff.type}**: ${ff.name}`);
    }
    lines.push("");
  }

  // Colors
  if (tokens.colors) {
    const entries = Object.entries(tokens.colors);
    if (entries.length) {
      lines.push("## Colors");
      lines.push("");
      lines.push("| Token | Value |");
      lines.push("|-------|-------|");
      for (const [name, value] of entries) {
        lines.push(`| \`${name}\` | ${value} |`);
      }
      lines.push("");
    }
  }

  // Spacing
  if (tokens.spacing) {
    const entries = Object.entries(tokens.spacing);
    if (entries.length) {
      lines.push("## Spacing");
      lines.push("");
      for (const [name, value] of entries) {
        lines.push(`- **${name}**: ${value}px`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("*Synced from [Styled Systems](https://styled.systems) — sanningen finns på ett ställe*");

  return lines.join("\n");
}
