/**
 * sync/generators/tailwind.ts — Tailwind CSS v3 config export
 *
 * Generates a `tailwind.config.js` CommonJS module that can be used as a
 * Tailwind preset or standalone config.
 *
 * Note: This is intentionally separate from the existing tailwind-css.ts
 * exporter, which generates a Tailwind v4 @theme CSS file. This generator
 * targets the v3 `tailwind.config.js` format for broader compatibility.
 */

import type { SyncableDesignSystem } from "../../versions/types.js";
import { extractTypographyScales } from "./tokens.js";

export type TailwindMode = "preset" | "full-config";

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Generates a Tailwind CSS config as a JavaScript module string.
 */
export function generateTailwindConfig(
  designSystem: SyncableDesignSystem,
  mode: TailwindMode = "preset"
): string {
  const { tokens } = designSystem;
  const theme: Record<string, unknown> = {};

  // Font families
  if (tokens.fontFamilies?.length) {
    theme.fontFamily = Object.fromEntries(
      tokens.fontFamilies.map((ff) => [ff.type, [ff.name, "sans-serif"]])
    );
  }

  // Type scales
  if (tokens.typography) {
    const scales = extractTypographyScales(tokens.typography);
    if (scales.length) {
      theme.fontSize = Object.fromEntries(
        scales.map((s) => [
          s.token,
          [`${s.fontSize}px`, { lineHeight: `${s.lineHeight}px` }],
        ])
      );
    }
  }

  // Colors
  if (tokens.colors) {
    theme.colors = { ...tokens.colors };
  }

  // Spacing
  if (tokens.spacing) {
    theme.spacing = Object.fromEntries(
      Object.entries(tokens.spacing).map(([k, v]) => [k, `${v}px`])
    );
  }

  const config =
    mode === "preset"
      ? { theme: { extend: theme } }
      : { theme, plugins: [] };

  return `/** @type {import('tailwindcss').Config} */
/** Generated by Styled Systems — ${new Date().toISOString()} */
module.exports = ${JSON.stringify(config, null, 2)}
`;
}
