name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write # Useful for provenance/security

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          # This tells GitHub to automatically create a valid .npmrc for you
          registry-url: "https://npm.pkg.github.com"
          scope: "@stysys"

      - run: npm ci

      - run: npm run build

      - name: Release
        env:
          # We use GITHUB_TOKEN for both.
          # It has the 'packages: write' permission from the block above.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
